### PR TITLE
Interview Questions Markdown

### PR DESCRIPTION
**Pull request by Akshay-jain22**

### CODE REVIEW

**Comment by Akshay-jain22** [comment]
Created a new branch **interview_questions_akshay_jain** and done suggested changes.
For any further suggestions, this PR should be considered :+1:

**Comment by Akshay-jain22** [comment]
Link to the Markdown : [Interview Questions](https://github.com/Akshay-jain22/IRIS-RoR-Bootcamp-2020/blob/interview_questions_akshay_jain/interview_questions.md)

**Comment by abhishekkumar2718** [comment]
> Created a new branch **interview_questions_akshay_jain** and done suggested changes.
> For any further suggestions, this PR should be considered +1

I wanted a new branch because it will have _just_ relevant changes - but this includes the solution for earlier sessions too! 

Did you merge the solutions to your local master/main branch? In any case, check out of the master as in IRIS-NITK repo.

**Comment by Akshay-jain22** [comment]
Nope, I haven't merged main branch with all solutions.
It may be because whenever i was creating a new branch, it was creating a copy of my previous branch.
So all the solutions keep on adding to new branches in my local repo.
That's why when i pushed to github repo branches, i added only the newly changed files not all ( `git add foldername filename` instead of `git add .` )

**Comment by Akshay-jain22** [comment]
Closing Branch, consider new pull request for any suggestions

**Pull request closed without merging**
