### PR TITLE
Session 4

### PR DESCRIPTION
**Pull request by harishA3**

### CODE REVIEW

**Comment by harishA3** [comment]
Screenshot 2021-01-26 122759

**Comment by harishA3** [comment]
Screenshot 2021-01-26 122901

**Comment by harishA3** [comment]
Screenshot 2021-01-26 123127

**Comment by harishA3** [comment]
Screenshot 2021-01-26 123025

**Comment by harishA3** [comment]
Screenshot 2021-01-26 123127

**Comment by harishA3** [comment]
Screenshot 2021-01-26 125232

**Comment by harishA3** [comment]
These are the files that i committed. i did git reset --soft HEAD~1 to remove the initial commit,in which i had committed wrong files .I should have maybe used git reset --hard. the session_3 commit which i had removed using git reset has also been committed

**Comment by abhishekkumar2718** [comment]
Hey, it looks great!

Try and attempt any of the bonus tasks

**Comment by harishA3** [comment]
Screenshot 2021-01-26 180627

**Comment by harishA3** [comment]
Screenshot 2021-01-26 180607

**Comment by harishA3** [comment]
Screenshot 2021-01-26 180607

**Comment by harishA3** [comment]
Screenshot 2021-01-26 183227

**Comment by harishA3** [comment]
I don't know why i added two navigation bars but now since,i have edited the application.html.erb file,it is a single navigation bar. I tried changing the colour of my nav_link. Although the colour of the nav link did change but it is not visible on the navigation until on click on the nav bar with  my cursor.

**Comment by harishA3** [comment]
Screenshot 2021-01-27 083545

**Comment by harishA3** [comment]
It works fine, now. The nav-link was maybe not visible as i was using the a tag which automatically sets the colour,based on the bg(the color of the other navbar that i created was bg-secondary), So,I just removed the a tag and changed it to link_to

**Pull request closed without merging**
