### PR TITLE
blogspot

### PR DESCRIPTION
**Pull request by harishA3**

### CODE REVIEW

**Comment by harishA3** [comment]
Screenshot 2021-01-20 075433

**Comment by harishA3** [comment]
Screenshot 2021-01-20 075643

**Comment by harishA3** [comment]
Screenshot 2021-01-20 080601

**Comment by harishA3** [comment]
Screenshot 2021-01-20 080815

**Comment by harishA3** [comment]
Screenshot 2021-01-20 080935

**Comment by harishA3** [comment]
these are some of the screenshots of the website. The picture where access denied is raised, is when a non registered user tries to read an article, which is not private or when a user (who is logged in) tries to edit or destroy articles(private/public),which are written by someone else .I created two users to check if this works and it did.

**Comment by abhishekkumar2718** [comment]
Hey, it looks good to me - awesome work! :partying_face:

**Pull request closed without merging**
