### PR TITLE
added session_1

### PR DESCRIPTION
**Pull request by madhavkumar1523**

### CODE REVIEW

**Comment by abhishekkumar2718** [comment]
Hey Madhav!

While creating the rails project, did you type `rails new hello_world --skip-git`? If not, go to `session_1/hello_world` and run `rm -rf .git`.

**Comment by madhavkumar1523** [comment]
> Hey Madhav!
> 
> While creating the rails project, did you type `rails new hello_world --skip-git`? If not, go to `session_1/hello_world` and run `rm -rf .git`.

I did it but nothing happened

**Comment by madhavkumar1523** [comment]
> Hey Madhav!
> 
> While creating the rails project, did you type `rails new hello_world --skip-git`? If not, go to `session_1/hello_world` and run `rm -rf .git`.

I ran rm -rf .git but nothing happened

**Comment by abhishekkumar2718** [comment]
If you are free right now, can you join the video call? https://meet.google.com/fqq-opvd-bps

**Pull request closed without merging**
